site_name: PKT Documentation
site_url: https://docs.pkt.cash/
site_author: PKT
site_description: "PKT is a stake-to-earn model, built on Coinbase’s Base blockchain, which rewards users that power its decentralized media network."
repo_url: "https://github.com/pkt-cash/pkt-docs"

plugins:
  - search

theme:
  name: moonstone
  custom_dir: custom_theme
  fluid_layout: false


nav:
  - Home: index.md
  - PKT Network:
    - What is PKT Network: network/what-is-network.md
    - An Open Ecosystem: network/open-ecosystem.md
  - Staking:
    - Stake to earn: stake/stake-earn.md
    - How to stake: stake/how-to.md
    - Community Liquidity: stake/community-liquidity.md
    - How to stake LP: stake/stake-lp.md
    - How to stake LP tokens: stake/stake-lp-tokens.md
  - Migration airdrop: airdrop.md
  - Infrastructure:
    - Infrastructure: infra/infrastructure.md
    - VPN Exit: infra/vpn-exit.md
    - Setup a Cjdns Node: infra/cjdns-node.md
    - PKT VPN: infra/vpn.md
    - Setup a VPN Exit Node: infra/exit-node.md
    - Setup a Domain Node: infra/domain-node.md
    - Setup a Nameserver Node: infra/nameserver.md
    - Setup a Route Server Node: infra/route-server.md
  - Domains:
    - Claim Domain: domains/claim-domain.md
    - Build a Website in PKT Network: domains/build-web.md
    - Accessing your cjdns website: domains/cjdns-web.md
  - Tokenomics:
    - Tokenomics: tokenomics/introduction.md
    - Initial Distribution: tokenomics/initial-distribution.md
    - Migration Airdrop: tokenomics/migration-airdrop.md
    - Token Supply: tokenomics/token-supply.md
    - Burned Coin Recapture Reconciliation: tokenomics/burned-coin-recapture-reconciliation.md
    - Proof-of-Stake Voting: tokenomics/proof-of-stake-voting.md
    - Development Team Allocation: tokenomics/dev-team.md
  - Affiliate: affiliate.md
  - How to buy PKT: buy-pkt-on-base.md
  - Wallets: wallets.md
  - Utility:
    - Introduction: utility.md
    - Content & Media: utility/content.md
    - Packet Hub: utility/packet-hub.md
    - BIA: utility/bia.md
    - Ecommerce: utility/ecommerce.md
    - Bandwidth Markets: utility/markets.md
    - Payments Transparency: utility/transparency.md
  - Governance:
    - Introduction: governance.md
    - Network Steward Charter: governance-nsc.md
  - Community:
    - Code of Conduct: community/code_of_conduct.md
    - Ethical Communication Guidelines: community/ethica-communication-guidelines.md
    - Examples to Avoid: community/avoid-examples.md
    - Better Examples: community/better-examples.md
  - Brand Assets: community/press-media-assets.md

markdown_extensions:
  - admonition
  - toc:
      permalink: false
  - attr_list

extra:
  meta:
    title: "PKT Documentation"
    description: "PKT is a stake-to-earn model, built on Coinbase’s Base blockchain, which rewards users that power its decentralized media network."

extra_css:
    - css/extra.css